name: microdf
channels:
- conda-forge
- PSLmodels
dependencies:
- codecov
- matplotlib
- numpy
- pandas
- pip
- pytest
- seaborn
- setuptools
- taxcalc
- pip:
  - matplotlib-label-lines
  - jupyter-book
