name: microdf
channels:
- conda-forge
dependencies:
- codecov
- flake8
- matplotlib
- numpy
- pandas
- pip
- pytest
- seaborn
- setuptools
- pip:
  - matplotlib-label-lines
  - jupyter-book
  - git+http://github.com/pslmodels/taxcalc.git
