package:
  name: microdf
  version: 0.0.0

build:
  number: 1

requirements:
  build:
    - python
    - matplotlib
    - numpy
    - pandas
    - seaborn
    - taxcalc

about:
  home: https://github.com/MaxGhenis/microdf