name: Test that Jupyter-Book builds
on: [push, pull_request]
jobs:
  build:
    if: github.repository == 'MaxGhenis/microdf'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          activate-environment: microdf
          environment-file: environment.yml
          python-version: 3.7
          auto-activate-base: false

      - name: Build  # Build Jupyter Book
        shell: bash -l {0}
        run: |
          pip install -e .
          jb build docs/.
